name: Build & Deploy Production

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Production
        run: npm run build swapi-frontend -- --configuration=production --base-href "/StarWars-angular/"

      - name: Deploy to GitHub Pages (Production)
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist/swapi-frontend/browser
          clean: true
          clean_exclude:
            qa
